# Autogenerated wrapper script for BSplines_jll for x86_64-w64-mingw32-libgfortran4
export libbsplines

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("BSplines")
JLLWrappers.@declare_library_product(libbsplines, "libbsplines.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libbsplines,
        "bin\\libbsplines.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
